apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashy-deployment
  labels:
    app: hashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashy
  template:
    metadata:
      labels:
        app: hashy
    spec:
      containers:
      - name: hashy
        image: gcr.io/mms-bdg-techsummit-d-prim/hashy-image:latest
        ports:
        - containerPort: 80
