---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "$service_name"
  labels:
    app: "$service_name"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "$service_name"
  template:
    metadata:
      labels:
        app: "$service_name"
    spec:
      containers:
        - name: "$service_name"
          image: "gcr.io/${project_id}/${service_name}-image:latest"
          ports:
            - containerPort: $port
          resources:
            requests:
              memory: "110Mi"
              cpu: "400m"
            limits:
              memory: "128Mi"
              cpu: "950m"
          env:
            - name: PORT
              value: "$port"
