apiVersion: apps/v1
kind: Deployment
metadata:
  name: "$service_name"
  labels:
    app: "$service_name"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "$service_name"
  template:
    metadata:
      labels:
        app: "$service_name"
    spec:
      containers:
      - name: "$service_name"
        image: "gcr.io/${project_id}/${service_name}-image:latest"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "110Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "900m"
