apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashy
  labels:
    app: hashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashy
  template:
    metadata:
      labels:
        app: hashy
    spec:
      containers:
      - name: hashy
        image: gcr.io/mms-bdg-techsummit-d-prim/hashy-image:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "110Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "900m"
